# Generated by Django 5.1.15 on 2026-05-20 16:43

import django_tenants.postgresql_backend.base
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'tenants_domain',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUniversity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('abbreviation', models.CharField(max_length=20)),
                ('university_type', models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('private', 'Private')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('sessions_per_year', models.PositiveSmallIntegerField(default=2)),
                ('current_session', models.CharField(blank=True, max_length=20)),
                ('current_semester', models.PositiveSmallIntegerField(default=1)),
                ('logo', models.TextField(blank=True, max_length=100)),
                ('primary_color', models.CharField(default='#1B4F72', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('data_protection_officer', models.EmailField(blank=True, max_length=254)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical University',
                'verbose_name_plural': 'historical Universities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('abbreviation', models.CharField(max_length=20)),
                ('university_type', models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('private', 'Private')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('sessions_per_year', models.PositiveSmallIntegerField(default=2)),
                ('current_session', models.CharField(blank=True, max_length=20)),
                ('current_semester', models.PositiveSmallIntegerField(default=1)),
                ('logo', models.ImageField(blank=True, upload_to='universities/logos/')),
                ('primary_color', models.CharField(default='#1B4F72', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('data_protection_officer', models.EmailField(blank=True, max_length=254)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'db_table': 'tenants_university',
            },
        ),
    ]
